import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Menu } from "@/components/menu";
import Link from "next/link";

import inicial from "./apple-touch-icon.ico";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Prova Part.2",
  description: "Generated by create next app",
  icons: inicial
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Menu op1="Primeira rota" op2="Segunda rota" op3="Terceira rota"></Menu>
        {children}
      </body>
    </html>
  );
}
